name: .NET

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    env:
      ProjectName: SunsUpStreamsUp

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            targetPlatform: linux-x64
            skipTests: false
          - os: windows-latest
            targetPlatform: win-x64
            skipTests: false
          - os: ubuntu-latest
            targetPlatform: osx-x64
            skipTests: false
          - os: ubuntu-latest
            targetPlatform: osx-arm64
            skipTests: true # can't run ARM64 executables on x64 Linux

    runs-on: ${{ matrix.os }}

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Initialize test reporting
      uses: testspace-com/setup-testspace@v1
      if: ${{ !matrix.skipTests }}
      with:
        domain: ${{ github.repository_owner }}

    - name: Restore from cache
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore
      run: dotnet restore --locked-mode --verbosity normal

    - name: Build
      run: dotnet build ${{ env.ProjectName }} --no-restore --configuration Release --runtime ${{ matrix.targetPlatform }} --no-self-contained

    - name: Test
      shell: bash
      if: ${{ !matrix.skipTests }}
      run: |
        testExitCode=0
        dotnet build Tests --configuration Release --runtime ${{ matrix.TargetPlatform }} --no-dependencies
        dotnet test --configuration Release --runtime ${{ matrix.targetPlatform }} --no-build --collect:"XPlat Code Coverage" --settings Tests/Tests.runsettings --logger "trx;LogFileName=TestResults.xml" || testExitCode=$?
        echo "TEST_EXIT_CODE=$testExitCode" >> $GITHUB_ENV
        cp Tests/TestResults/*/coverage.info Tests/TestResults
        exit 0

    - name: Upload test report
      if: ${{ !matrix.skipTests }}
      run: testspace Tests/TestResults/TestResults.xml

    - name: Upload coverage
      uses: coverallsapp/github-action@master
      if: ${{ !matrix.skipTests }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: Tests/TestResults/coverage.info

    - name: Stop if tests failed
      if: ${{ !matrix.skipTests }}
      run: exit ${{ env.TEST_EXIT_CODE }}

    - name: Publish
      run: dotnet publish ${{ env.ProjectName }} --no-build --configuration Release -p:PublishSingleFile=true --runtime ${{ matrix.TargetPlatform }} --no-self-contained
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ProjectName }}-${{ matrix.TargetPlatform }}
        path: |
          ${{ env.ProjectName }}/bin/Release/net8.0/${{ matrix.TargetPlatform }}/publish/${{ env.ProjectName }}
          ${{ env.ProjectName }}/bin/Release/net8.0/${{ matrix.TargetPlatform }}/publish/${{ env.ProjectName }}.exe
          ${{ env.ProjectName }}/bin/Release/net8.0/${{ matrix.TargetPlatform }}/publish/appsettings.json
        if-no-files-found: error
